# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

imageConvParallel <- function(img, kernel) {
    .Call('_imageConvParallel_imageConvParallel', PACKAGE = 'imageConvParallel', img, kernel)
}

